language: php

php:
  - 7.1
  - 7.2
  - 7.3

# to support hhvm
dist: trusty

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
  - $HOME/.composer/cache

env:
  matrix:
  - COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
  - COMPOSER_OPTIONS=""

install:
- travis_retry composer self-update && composer --version
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- travis_retry composer update --prefer-dist --no-interaction $COMPOSER_OPTIONS

script:
- sh ./phpcs.sh
- php ./vendor/bin/codecept run unit -d --coverage --coverage-xml

after_success:
- php ./vendor/bin/php-coveralls -v --exclude-no-stmt -c .coveralls.yml
