language: php

php:
  - 7.1
  - 7.2
  - 7.3

# to support hhvm
dist: trusty

# faster builds on new travis setup not using sudo
sudo: false

services:
    - mysql

# cache vendor dirs
cache:
  directories:
  - $HOME/.composer/cache

env:
  matrix:
      - COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
      - COMPOSER_OPTIONS=""
  global:
      - DB_TEST_DSN="mysql:host=localhost;dbname=database"
      - DB_USERNAME=travis
      - DB_PASSWORD=

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `database`;'

install:
- travis_retry composer self-update && composer --version
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- travis_retry composer update --prefer-dist --no-interaction $COMPOSER_OPTIONS
- php tests/bin/yii migrate --interactive=0

script:
- sh ./phpcs.sh
- php ./vendor/bin/codecept run unit -d --coverage --coverage-xml

after_success:
- php ./vendor/bin/php-coveralls -v --exclude-no-stmt -c .coveralls.yml
